int led = 13;
int resetPin = 12;

#include "Adafruit_HT1632.h"

#define HT_DATA 2
#define HT_WR   3
#define HT_CS   4
#define HT_CS2  5

Adafruit_HT1632LEDMatrix matrix = Adafruit_HT1632LEDMatrix(HT_DATA, HT_WR, HT_CS);

void setup() {
  pinMode(LED_BUILTIN, OUTPUT);
  Serial.begin(9600);
  matrix.begin(ADA_HT1632_COMMON_16NMOS);
  delay(500);
  matrix.clearScreen();
  matrix.setTextWrap(false);
  digitalWrite(resetPin, HIGH);
  delay(100);
  pinMode(led, OUTPUT);
  pinMode(resetPin, OUTPUT);
  matrix.setTextSize(2);
}

void loop() {

  if (digitalRead(8) == HIGH)
  {
    // D6 = Right
    matrix.setCursor(0, 1);
    matrix.print(">>");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print(">>");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print(">>");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print(">>");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print(">>");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print(">>");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print(">>");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print(">>");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print(">>");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print(">>");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print(">>");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print(">>");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print(">>");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print(">>");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print(">>");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print(">>");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print(">>");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print(">>");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print(">>");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print(">>");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print(">>");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print(">>");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print(">>");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print(">>");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print(">>");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print(">>");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
  }
  if (digitalRead(9) == HIGH)
  {
    //D7 = Left
    matrix.setCursor(0, 1);
    matrix.print("<<");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print("<<");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print("<<");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print("<<");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print("<<");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print("<<");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print("<<");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print("<<");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print("<<");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print("<<");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print("<<");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print("<<");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print("<<");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print("<<");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print("<<");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print("<<");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print("<<");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print("<<");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print("<<");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print("<<");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print("<<");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print("<<");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print("<<");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print("<<");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print("<<");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    matrix.setCursor(0, 1);
    matrix.print("<<");
    matrix.writeScreen();
    delay(100);
    matrix.clearScreen();
    delay(100);
    
      
  }

}

